#!/bin/bash
# Extract reusable fix patterns from successful upgrade fix.sql
# Usage: ./generate_fix_pattern.sh --fix-sql <path_to_fix.sql> --output <output_pattern.sql>
#
# This script extracts ONLY the reusable SQL fixes that can be applied
# to other databases BEFORE running upgrade.
#
# NOTE: Use the fix.sql that PROVED successful during upgrade process.
# Not hardcoded to fix_run001.sql - use any proven fix file.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

usage() {
    cat << EOF
Extract Reusable Fix Patterns from fix_run001.sql

USAGE:
    $0 --fix-sql <path> --output <path> [OPTIONS]

ARGUMENTS:
    --fix-sql   Path to successful fix_run001.sql
    --output    Output path for fix pattern

OPTIONS:
    --description "Text"    Add description header
    --db-prefix PREFIX       Database prefix for module names
    --help                  Show this help

EXAMPLES:
    # Basic extraction
    $0 --fix-sql ./migration/upgrade_logs/run_001/fix_run001.sql \
       --output ./fix_pattern.sql

    # With description
    $0 --fix-sql ./fix.sql --output ./roedl_fixes.sql \
       --description "Roedl v15 to v19 - View + Module fixes"

EOF
    exit 0
}

# Parse arguments
FIX_SQL=""
OUTPUT_FILE=""
DESCRIPTION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --fix-sql) FIX_SQL="$2"; shift 2 ;;
        --output) OUTPUT_FILE="$2"; shift 2 ;;
        --description) DESCRIPTION="$2"; shift 2 ;;
        --help) usage ;;
        *) echo "Unknown: $1"; usage ;;
    esac
done

if [[ -z "$FIX_SQL" || -z "$OUTPUT_FILE" ]]; then
    echo "Error: --fix-sql and --output are required"
    usage
fi

if [[ ! -f "$FIX_SQL" ]]; then
    echo "Error: File not found: $FIX_SQL"
    exit 1
fi

echo "Extracting fix patterns from: $FIX_SQL"

# Create output file
cat > "$OUTPUT_FILE" << 'HEADER'
-- ============================================================
-- REUSABLE FIX PATTERN
-- Generated by: odoo-db-migration skill
-- ============================================================
-- This file contains SQL fixes that can be applied to other
-- databases BEFORE running upgrade.odoo.com
--
-- USAGE:
--   psql -h localhost -U odoo -d target_db -f this_file.sql
-- ============================================================

HEADER

echo "-- Source: $FIX_SQL" >> "$OUTPUT_FILE"
echo "-- Generated: $(date)" >> "$OUTPUT_FILE"
[[ -n "$DESCRIPTION" ]] && echo "-- Description: $DESCRIPTION" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract and categorize fixes

echo "Analyzing fixes..."

# Count different types of fixes
VIEW_FIXES=$(grep -c "ir_ui_view.*active.*false" "$FIX_SQL" || echo "0")
MODULE_FIXES=$(grep -c "ir_module_module.*state.*'to upgrade'" "$FIX_SQL" || echo "0")
TRACKING_TABLES=$(grep -c "CREATE TABLE.*migration" "$FIX_SQL" || echo "0")
INSERT_FIXES=$(grep -c "INSERT INTO.*migration" "$FIX_SQL" || echo "0")

echo ""
echo "Found:"
echo "  - View fixes: $VIEW_FIXES"
echo "  - Module fixes: $MODULE_FIXES"
echo "  - Tracking tables: $TRACKING_TABLES"
echo "  - Insert statements: $INSERT_FIXES"
echo ""

# Extract VIEW fixes (disable broken views)
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "-- VIEW FIXES: Disable broken inherited views" >> "$OUTPUT_FILE"
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Find bulk view disable statements
grep -E "^UPDATE ir_ui_view SET active = false.*IN \(" "$FIX_SQL" >> "$OUTPUT_FILE" 2>/dev/null || true

# Find view-specific disables by ID
grep -E "^UPDATE ir_ui_view.*WHERE id IN \(" "$FIX_SQL" >> "$OUTPUT_FILE" 2>/dev/null || true

# Extract MODULE fixes (set custom modules to 'to upgrade')
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "-- MODULE FIXES: Mark custom modules for migration" >> "$OUTPUT_FILE"
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Find module state updates
grep -E "^UPDATE ir_module_module SET state = 'to upgrade'" "$FIX_SQL" >> "$OUTPUT_FILE" 2>/dev/null || true

# Extract module names for documentation
MODULE_NAMES=$(grep -oP "name IN \('\K[^']+'" "$FIX_SQL" | tr "'" "\n" | grep -v "^$" | head -20 || echo "")

if [[ -n "$MODULE_NAMES" ]]; then
    echo "-- Custom modules marked for migration:" >> "$OUTPUT_FILE"
    echo "$MODULE_NAMES" | while read -r mod; do
        [[ -n "$mod" ]] && echo "--   - $mod" >> "$OUTPUT_FILE"
    done
fi

# Extract TRACKING TABLE creation (optional - for audit)
echo "" >> "$OUTPUT_FILE"
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "-- TRACKING TABLES: Audit trail for migration" >> "$OUTPUT_FILE"
echo "-- ============================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract CREATE TABLE statements
awk '/^CREATE TABLE.*migration/{found=1} found{print} /^;$/{if(found) found=0}' "$FIX_SQL" >> "$OUTPUT_FILE" 2>/dev/null || true

# Extract INSERT statements for tracking
awk '/^INSERT INTO.*migration/{found=1} found{print} /^;$/{if(found) found=0}' "$FIX_SQL" >> "$OUTPUT_FILE" 2>/dev/null || true

# Add usage instructions at the end
cat >> "$OUTPUT_FILE" << 'FOOTER'

-- ============================================================
-- APPLYING THESE FIXES
-- ============================================================
-- Before applying, verify:
-- 1. Database is backed up
-- 2. Target Odoo version matches (v15 -> v19 typically)
-- 3. Custom module names match your database
--
-- Apply with:
--   psql -h localhost -U odoo -d target_database -f this_file.sql
--
-- Or include in upgrade script:
--   ./odoo_reusable_upgrade.sh newdb.sql 19.0 --fix-pattern this_file.sql
-- ============================================================
FOOTER

echo ""
echo -e "${GREEN}Fix pattern extracted successfully!${NC}"
echo "Output: $OUTPUT_FILE"
echo ""
echo "Usage:"
echo "  # Apply to other database:"
echo "  psql -h localhost -U odoo -d target_db -f $OUTPUT_FILE"
echo ""
echo "  # Use with upgrade script:"
echo "  ./odoo_reusable_upgrade.sh newdb.sql 19.0 --fix-pattern $OUTPUT_FILE"
