#!/usr/bin/env python3
"""
Generate comprehensive migration report in Markdown format.

Usage:
    python3 generate_migration_report.py \
        --analysis ./module_migration/analysis.json \
        --fixes ./module_migration/fixes.json \
        --module ./module_migration/roedl/asb_project_followers \
        --output ./module_migration/roedl/asb_project_followers/MIGRATION_REPORT.md
"""

import json
import argparse
from pathlib import Path
from datetime import datetime


def generate_report(analysis: dict, fixes: dict, module_path: Path) -> str:
    """Generate comprehensive migration report."""

    module_name = analysis.get('module_name', 'Unknown')
    source_version = analysis.get('source_version', 'unknown')
    target_version = analysis.get('target_version', 'unknown')

    report = f"""# Module Migration Report: {module_name}

## Summary

| Aspect | Total | Auto-Fixed | Manual Review |
|--------|-------|------------|---------------|
"""

    # Calculate summary
    summary = analysis.get('summary', {})
    model_changes = analysis.get('model_changes', {})
    field_changes = analysis.get('field_changes', [])
    fixes_data = fixes.get('fixes', [])
    manual_review = fixes.get('manual_review_required', [])

    auto_fixed = len([f for f in fixes_data if f.get('auto_apply')])
    manual_needed = len(manual_review) + len([f for f in fixes_data if not f.get('auto_apply')])

    report += f"| Models | {len(model_changes)} | {len([m for m in model_changes.values() if m.get('change_type') == 'RENAMED'])} | {len([m for m in model_changes.values() if m.get('change_type') == 'REMOVED'])} |\n"
    report += f"| Fields | {len(field_changes)} | 0 | {len(field_changes)} |\n"
    report += f"| Fixes | {len(fixes_data)} | {auto_fixed} | {manual_needed} |\n"

    report += f"""
**Migration**: {source_version} → {target_version}
**Generated**: {datetime.now().strftime('%Y-%m-%d')}

---

## Changes Detail

### Models

| Model | Change Type | Replacement | Confidence | Details |
|-------|-------------|-------------|------------|---------|
"""

    if model_changes:
        for model_name, change in model_changes.items():
            change_type = change.get('change_type', 'UNKNOWN')
            replacement = change.get('replacement', '-')
            confidence = change.get('confidence', 0)
            details = ', '.join(change.get('details', [])) or '-'

            icon = '🔴' if change_type == 'REMOVED' else '🟡' if change_type == 'RENAMED' else '🟢'

            report += f"| {model_name} | {icon} {change_type} | {replacement} | {confidence}% | {details} |\n"
    else:
        report += "| *No model changes detected* | | | | |\n"

    report += """

### Fields

| Model | Field | Change Type | Old Value | New Value |
|-------|-------|-------------|-----------|-----------|
"""

    if field_changes:
        for fc in field_changes:
            report += f"| {fc.get('model_name', 'unknown')} | {fc.get('field_name', 'unknown')} | {fc.get('change_type', 'UNKNOWN')} | {fc.get('old_value', '-')} | {fc.get('new_value', '-')} |\n"
    else:
        report += "| *No field changes detected* | | | | |\n"

    report += """

---

## Auto-Applied Fixes

"""

    if fixes_data:
        applied_fixes = [f for f in fixes_data if f.get('auto_apply')]
        if applied_fixes:
            for fix in applied_fixes:
                report += f"""### {fix['file']}

- **Type**: {fix.get('type', 'UNKNOWN')}
- **Description**: {fix.get('description', '')}

```python
# Old
{fix.get('old_code', '')}

# New
{fix.get('new_code', '')}
```

"""
        else:
            report += "*No auto-applicable fixes found.*\n"
    else:
        report += "*No fixes generated.*\n"

    report += """

---

## Manual Review Required

"""

    if manual_review:
        for idx, review in enumerate(manual_review, 1):
            report += f"""### {idx}. {review['file']}

- **Issue**: {review['issue']}
- **Suggestion**: {review['suggestion']}

"""
    else:
        report += "*No manual review items.*\n"

    report += """

---

## Dependencies

| Type | Reference | Status |
|------|-----------|--------|
"""

    # Add dependency info from analysis
    # (This would come from the blueprint, but for now we show placeholder)

    report += f"""
- **Source Version**: {source_version}
- **Target Version**: {target_version}

---

*Generated by odoo-module-migration tool*
"""

    return report


def main():
    parser = argparse.ArgumentParser(description='Generate migration report')
    parser.add_argument('--analysis', required=True, help='Path to analysis JSON')
    parser.add_argument('--fixes', help='Path to fixes JSON')
    parser.add_argument('--module', required=True, help='Path to module directory')
    parser.add_argument('--output', '-o', required=True, help='Output Markdown file')

    args = parser.parse_args()

    # Load analysis
    analysis_path = Path(args.analysis)
    if not analysis_path.exists():
        print(f"Error: Analysis file not found: {args.analysis}")
        return

    analysis = json.loads(analysis_path.read_text())

    # Load fixes (optional)
    fixes = {'fixes': [], 'manual_review_required': []}
    if args.fixes:
        fixes_path = Path(args.fixes)
        if fixes_path.exists():
            fixes = json.loads(fixes_path.read_text())

    # Module path
    module_path = Path(args.module)

    print(f"Generating report for {analysis.get('module_name')}")

    # Generate report
    report = generate_report(analysis, fixes, module_path)

    # Save report
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(report)

    print(f"\n✅ Report generated!")
    print(f"   Output: {args.output}")


if __name__ == '__main__':
    main()
