#!/usr/bin/env python3
"""
Generate model migration checklist.

Usage:
    python3 generate_model_checklist.py \
        --removed-models /tmp/removed_models.json \
        --output model_migration_checklist.md
"""

import json
import argparse
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass
from typing import List


@dataclass
class ModelIssue:
    model_name: str
    action: str
    new_model: str | None
    confidence: float | None
    level: str
    affected_modules: List[str]


def load_removed_models(json_path: str) -> List[dict]:
    """Load removed models dari JSON."""
    with open(json_path, 'r') as f:
        return json.load(f)


def generate_checklist(removed_models_json: str, output_path: str):
    """Generate markdown checklist."""
    data = json.load(open(removed_models_json))

    removed = data.get('removed_models', [])
    affected = data.get('affected_modules', {})
    inheritance_issues = data.get('inheritance_issues', {})
    xml_references = data.get('xml_references', {})

    # Group by status
    auto_resolved = []
    needs_review = []

    # Build set of models with inheritance issues for display
    inheritance_models = set()
    for model in inheritance_issues.keys():
        inheritance_models.add(model)

    for model in xml_references.keys():
        inheritance_models.add(model)

    for item in removed:
        model = item['model_name']
        action = item['action']

        # Determine status based on inheritance issues
        has_inheritance = model in inheritance_models or model in affected

        if action == 'renamed':
            level = 'HIGH'
            status = '✅ AUTO-RESOLVED' if has_inheritance else '📝 renamed'
        elif has_inheritance:
            level = '🔴 CRITICAL'
            status = '⚠️ NEEDS FIX'
        else:
            level = 'NEEDS_ANALYSIS'
            status = '❌ removed'

        # Get affected files
        affected_files = []
        if model in inheritance_issues:
            affected_files.extend(inheritance_issues[model])
        if model in xml_references:
            affected_files.extend(xml_references[model])

        needs_review.append(ModelIssue(
            model_name=model,
            action=action,
            new_model=item.get('new_model'),
            confidence=None,
            level=level,  # Use the level variable, not status
            affected_modules=affected_files
        ))

    # Count critical issues
    critical_count = sum(1 for i in needs_review if i.level == '🔴 CRITICAL')

    # Generate markdown
    md = f"""# Model Migration Checklist

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Summary

| Metric | Count |
|--------|-------|
| Total Removed/Renamed Models | {len(removed)} |
| Modules with Inheritance Issues | {len(inheritance_issues)} |
| XML References to Fix | {len(xml_references)} |
| 🔴 CRITICAL (Needs Fix) | {critical_count} |

## 🚨 CRITICAL: Models with Inheritance Issues

"""

    if inheritance_issues:
        for model, files in inheritance_issues.items():
            md += f"### {model}\n"
            md += f"**Files yang perlu diupdate:**\n"
            for f in files:
                md += f"- `{f}`\n"
            md += "\n"
    else:
        md += "_Tidak ada_\n\n"

    md += """
## 📄 XML References to Update

"""
    if xml_references:
        for model, files in xml_references.items():
            md += f"### {model}\n"
            md += f"**XML files:**\n"
            for f in files:
                md += f"- `{f}`\n"
            md += "\n"
    else:
        md += "_Tidak ada_\n\n"

    md += """## All Models Requiring Analysis

| Model | Action | Status | Files Affected |
|-------|--------|--------|----------------|
"""

    for issue in needs_review:
        status_icon = issue.level
        files = ', '.join(issue.affected_modules[:2]) if issue.affected_modules else '-'
        if len(issue.affected_modules) > 2:
            files += f' (+{len(issue.affected_modules)-2} more)'

        md += f"| {issue.model_name} | {issue.action} | {status_icon} | {files} |\n"

    md += """
## Required Actions

### 🔴 CRITICAL - Fix Inheritance:

1. **Python Files:**
   ```python
   # Before (v15)
   _inherit = 'mail.wizard.invite'

   # After (v17) - cari replacement:
   # - mail.wizard.invite → mail.wizard.followers
   # - Note: cek known_deprecations.py untuk mapping lengkap
   _inherit = 'mail.wizard.followers'
   ```

2. **XML Files:**
   - Update `model="..."` attributes
   - Cek view definitions yang merefer ke model lama

### Testing:
- Wizard workflow mungkin berubah
- Verify all buttons/actions work
- Test di database yang sudah di-upgrade

---
*Generated by odoo-module-migration skill*
"""

    # Write output
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(md)

    print(f"✅ Checklist generated: {output_path}")
    print(f"   - {len(removed)} models analyzed")
    print(f"   - 🔴 {critical_count} CRITICAL issues found")


def main():
    parser = argparse.ArgumentParser(description='Generate model migration checklist')
    parser.add_argument('--removed-models', required=True, help='JSON dari parse_upgrade_removals.py')
    parser.add_argument('--output', '-o', required=True, help='Output markdown file')

    args = parser.parse_args()
    generate_checklist(args.removed_models, args.output)


if __name__ == '__main__':
    main()
