#!/usr/bin/env python3
"""
Generate CLAUDE.md for Odoo migration with comprehensive breaking changes.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional


# Known breaking changes by Odoo version
BREAKING_CHANGES = {
    '12': {
        'deprecated': [
            '@api.multi - use @api.model instead',
            'workflow module - removed, use states',
            'cr.execute - use self._cr.execute()',
            'api.cr - use self._cr',
        ],
        'fields': [
            'Many2one: ondelete="cascade" now required for required relations',
            'Binary field: store=True now mandatory for large files',
        ],
        'views': [
            'View arch must use proper XML structure',
            'Button attrs changed to use dict format',
        ],
    },
    '13': {
        'deprecated': [
            'fields.text is now default for Text field',
            'report_paperformat now in separate module',
        ],
        'fields': [
            ' Monetary field requires currency_field',
            'Date/DateTime: formatting changed',
        ],
    },
    '14': {
        'deprecated': [
            'web_editor colors deprecated',
        ],
        'fields': [
            'Binary: new FileStorage handling',
        ],
    },
    '15': {
        'deprecated': [
            'Some legacy view attributes removed',
        ],
        'fields': [
            'Python 3.8+ required',
        ],
    },
    '16': {
        'deprecated': [
            'Many2one: ondelete="set null" behavior changed',
            'mail: legacy notification types removed',
        ],
        'fields': [
            'Image: new resize handling',
        ],
    },
    '17': {
        'deprecated': [
            'request.cr - use request.env.cr',
            'fields.Date.context_today - use fields.Date.today()',
            'osv.Model - use odoo.models.Model',
            'osv.TransientModel - use odoo.models.TransientModel',
            'cr.dbname - use env.cr.dbname',
        ],
        'fields': [
            'New field tracking mechanism',
        ],
        'views': [
            'Form view: new sheet layout required',
        ],
    },
    '18': {
        'deprecated': [
            'XMLRPC deprecated',
            'Legacy web controllers removed',
        ],
        'fields': [],
        'views': [],
    },
}


def get_breaking_changes_for_version(source_ver: str, target_ver: str) -> Dict[str, List[str]]:
    """Get breaking changes for the migration path."""
    source_num = int(source_ver.split('.')[0])
    target_num = int(target_ver.split('.')[0])

    result = {
        'deprecated': [],
        'fields': [],
        'views': [],
    }

    for ver in range(source_num + 1, target_num + 1):
        ver_str = str(ver)
        if ver_str in BREAKING_CHANGES:
            changes = BREAKING_CHANGES[ver_str]
            result['deprecated'].extend(changes.get('deprecated', []))
            result['fields'].extend(changes.get('fields', []))
            result['views'].extend(changes.get('views', []))

    return result


def generate_module_checklist(module_name: str) -> str:
    """Generate manual review checklist for a module."""
    return f"""
### {module_name}

- [ ] Review all `@api.multi` decorators - change to `@api.model`
- [ ] Check all `cr.execute()` calls - use `self._cr.execute()`
- [ ] Verify `self.env.cr` usage - may need `self._cr`
- [ ] Check workflow usage - replace with state field
- [ ] Verify view XML inheritance
- [ ] Test all buttons and actions
- [ ] Check field ondelete behavior
- [ ] Verify Many2one relationships
- [ ] Test computed fields
- [ ] Check onchange methods
"""


def generate_claude_md(
    modules: List[str],
    source: str,
    target: str,
    output_dir: str = ".",
    breaking_changes_json: Optional[str] = None,
    custom_modules_path: Optional[str] = None,
) -> str:
    """Generate comprehensive CLAUDE.md file."""

    # Get breaking changes
    changes = get_breaking_changes_for_version(source, target)

    # Load breaking changes from comparison if available
    external_changes = {}
    if breaking_changes_json and os.path.exists(breaking_changes_json):
        try:
            with open(breaking_changes_json, 'r') as f:
                external_changes = json.load(f)
        except Exception:
            pass

    content = f"""# Odoo Migration Context

> Generated by Odoo Migration Skill
> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Migration Info

| Property | Value |
|----------|-------|
| Source Version | {source} |
| Target Version | {target} |
| Status | In Progress |

## Modules

"""

    # List modules
    for module in modules:
        module_name = Path(module).name
        content += f"- **{module_name}**: Pending review\n"

    # Breaking Changes Section
    content += """
---

## Breaking Changes

"""

    if external_changes.get('summary', {}).get('deprecated_apis'):
        content += "### Deprecated APIs (from Version Comparison)\n\n"
        for api in external_changes['summary']['deprecated_apis']:
            content += f"- **{api['api']}**: Use {api['replacement']} (deprecated since v{api['since']})\n"
        content += "\n"

    if changes['deprecated']:
        content += "### Common Deprecated Patterns\n\n"
        for change in changes['deprecated']:
            content += f"- {change}\n"
        content += "\n"

    if changes['fields']:
        content += "### Field Changes\n\n"
        for change in changes['fields']:
            content += f"- {change}\n"
        content += "\n"

    if changes['views']:
        content += "### View Changes\n\n"
        for change in changes['views']:
            content += f"- {change}\n"
        content += "\n"

    # Manual Review Checklist
    content += """---

## Manual Review Checklist

"""
    for module in modules:
        module_name = Path(module).name
        content += generate_module_checklist(module_name)

    # Pre-Migration Tasks
    content += """
---

## Pre-Migration Tasks

- [ ] Backup database
- [ ] Commit all custom modules to git
- [ ] Verify Python version (need 3.8+ for Odoo 17+)
- [ ] Check all dependencies available in target version
- [ ] Verify contract number for upgrade.odoo.com
- [ ] Create database dump including filestore
- [ ] Test migration in staging environment first

"""

    # Post-Migration Tasks
    content += """---

## Post-Migration Tasks

- [ ] Run tests
- [ ] Check all views load correctly
- [ ] Verify workflows function properly
- [ ] Test all CRUD operations
- [ ] Check scheduled actions
- [ ] Verify email/notification templates
- [ ] Test import/export functionality
- [ ] Check access rights (ACL)
- [ ] Verify report generation
- [ ] Test web services (API)

"""

    # Database Upgrade
    content += f"""---

## Database Upgrade

### Test Upgrade
```bash
python <(curl -s https://upgrade.odoo.com/upgrade) test \\
    -i <dump_file> \\
    -t {target} \\
    -c <contract_number>
```

### Production Upgrade
```bash
python <(curl -s https://upgrade.odoo.com/upgrade) production \\
    -i <dump_file> \\
    -t {target} \\
    -c <contract_number>
```

"""

    # External Breaking Changes Report
    if breaking_changes_json and os.path.exists(breaking_changes_json):
        content += f"""---

## Version Comparison Report

Full breaking changes report available at:
`{breaking_changes_json}`

"""
        if external_changes.get('summary', {}).get('removed_modules'):
            content += "### Removed Modules\n\n"
            for mod in external_changes['summary']['removed_modules']:
                content += f"- `{mod}` - find alternative or remove dependency\n"

    # Notes
    content += """---

## Notes

Add project-specific notes here.

"""

    # Validate inputs
    if not modules:
        raise ValueError("At least one module must be provided")
    if not source or not target:
        raise ValueError("Source and target versions must be provided")

    # Write file
    output_path = os.path.join(output_dir, "CLAUDE.md")
    try:
        with open(output_path, 'w') as f:
            f.write(content)
    except OSError as e:
        raise OSError(f"Failed to write CLAUDE.md: {e}") from e

    return output_path


def main() -> None:
    import sys
    import argparse

    parser = argparse.ArgumentParser(
        description='Generate CLAUDE.md for Odoo migration'
    )
    parser.add_argument('source_version', help='Source Odoo version (e.g., 15.0)')
    parser.add_argument('target_version', help='Target Odoo version (e.g., 17.0)')
    parser.add_argument('modules', nargs='+', help='Module names or paths')
    parser.add_argument(
        '-o', '--output-dir',
        default='.',
        help='Output directory (default: current directory)'
    )
    parser.add_argument(
        '-b', '--breaking-changes',
        help='Path to breaking changes JSON from comparison script'
    )

    args = parser.parse_args()

    source = args.source_version
    target = args.target_version
    modules = args.modules

    # Validate source and target versions
    if not source or not target:
        print("Error: Source and target versions must be provided")
        sys.exit(1)

    # Validate modules
    if not modules:
        print("Error: At least one module must be provided")
        sys.exit(1)

    try:
        output_path = generate_claude_md(
            modules,
            source,
            target,
            args.output_dir,
            args.breaking_changes,
        )
        print(f"Generated: {output_path}")
    except FileNotFoundError as e:
        print(f"Error: Could not write file - {e}")
        sys.exit(1)
    except PermissionError as e:
        print(f"Error: Permission denied - {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
