#!/usr/bin/env python3
"""
Generate model migration checklist.

Usage:
    python3 generate_model_checklist.py \
        --removed-models /tmp/removed_models.json \
        --output model_migration_checklist.md
"""

import json
import argparse
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass
from typing import List


@dataclass
class ModelIssue:
    model_name: str
    action: str
    new_model: str | None
    confidence: float | None
    level: str
    affected_modules: List[str]


def load_removed_models(json_path: str) -> List[dict]:
    """Load removed models dari JSON."""
    with open(json_path, 'r') as f:
        return json.load(f)


def generate_checklist(removed_models_json: str, output_path: str):
    """Generate markdown checklist."""
    data = json.load(open(removed_models_json))

    removed = data.get('removed_models', [])
    affected = data.get('affected_modules', {})

    # Group by status
    auto_resolved = []
    needs_review = []

    for item in removed:
        model = item['model_name']
        action = item['action']

        # Simple heuristic: jika ada di known deprecations dan confidence > 70
        # Kita assume sudah resolved, tapi tetep perlu review
        if action == 'renamed':
            needs_review.append(ModelIssue(
                model_name=model,
                action='renamed',
                new_model=item.get('new_model'),
                confidence=None,
                level='HIGH',
                affected_modules=affected.get(model, [])
            ))
        else:
            needs_review.append(ModelIssue(
                model_name=model,
                action=action,
                new_model=None,
                confidence=None,
                level='NEEDS_ANALYSIS',
                affected_modules=affected.get(model, [])
            ))

    # Generate markdown
    md = f"""# Model Migration Checklist

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Summary

| Metric | Count |
|--------|-------|
| Total Removed/Renamed Models | {len(removed)} |
| Affected Modules | {len(affected)} |
| Auto-Resolved | {len(auto_resolved)} |
| Manual Review Needed | {len(needs_review)} |

## Affected Modules

"""

    for module, models in affected.items():
        md += f"- **{module}**: depends on {', '.join(models)}\n"

    md += """
## Models Requiring Analysis

| Model | Action | Status | Affected Modules |
|-------|--------|--------|-----------------|
"""

    for issue in needs_review:
        status_icon = '❌' if issue.action == 'removed' else '📝'
        modules = ', '.join(issue.affected_modules) if issue.affected_modules else '-'
        new_model = issue.new_model or '-'

        md += f"| {issue.model_name} | {status_icon} {issue.action} | {issue.level} | {modules} |\n"

    md += """
## Required Actions

### For Each Affected Module:

1. **Update Inheritance**
   - Check model definition di source code
   - Replace: `from . import model_name` jika needed

2. **Update Views**
   - Cari view yang merefer ke model lama
   - Update model attribute di XML

3. **Test Functionality**
   - Wizard workflow mungkin berubah
   - Verify all buttons/actions work

## Example Fix: mail.wizard.invite → mail.wizard.followers

```python
# Before (v15)
class MyWizard(models.TransientModel):
    _inherit = 'mail.wizard.invite'

# After (v17)
class MyWizard(models.TransientModel):
    _inherit = 'mail.wizard.followers'
```

---
*Generated by odoo-module-migration skill*
"""

    # Write output
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(md)

    print(f"✅ Checklist generated: {output_path}")
    print(f"   - {len(removed)} models analyzed")
    print(f"   - {len(affected)} modules affected")


def main():
    parser = argparse.ArgumentParser(description='Generate model migration checklist')
    parser.add_argument('--removed-models', required=True, help='JSON dari parse_upgrade_removals.py')
    parser.add_argument('--output', '-o', required=True, help='Output markdown file')

    args = parser.parse_args()
    generate_checklist(args.removed_models, args.output)


if __name__ == '__main__':
    main()
